# Generated by Django 3.1.3 on 2021-01-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('ingreso', models.IntegerField(verbose_name='Cantidad Ingresada')),
                ('fecha_egreso', models.DateTimeField(null=True)),
                ('egreso', models.IntegerField(null=True, verbose_name='Cantidad Egresada')),
                ('ubicacion_actual', models.CharField(max_length=15, null=True, verbose_name='Tipo')),
                ('ubicacion_anterior', models.CharField(max_length=15, null=True, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
